[package]
name = "chapter-4"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly = "0.5.0"
ark-bn254 = "0.5.0"
ark-std = { version = "0.5.0", features = ["parallel"]}
ark-ff = "0.5.0"
rand = "0.8.5"